name: Deploy and Seed Database

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js and npm
        run: |
          sudo apt update
          sudo apt install -y nodejs npm
          node -v
          npm -v

      - name: Install Dependencies
        run: |
          cd server
          npm install

      - name: Debug Connection String
        run: echo $DB_CONNECTION_STRING

      - name: Run Seed Script
        env:
          DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
        run: |
          npm run seed

      - name: Enable Debug Logs
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
